- id: sfdx-apex-test-run
  name: SFDX APEX Tests Run
  description: Runs SFDX APEX tests agains the folder with human report
  entry: pre-commit/sfdx-apex-test-run
  language: script
  types: [directory]
