---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: projectatomic/dockerfile-lint
    tag: 'latest'

inputs:
- name: src

params: 
  SEARCH_PATH: "repo/docker-images"

run:
  path: src/docker/lint/lint_dockerfile.sh
