---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource
    tag: 'latest'

inputs:
- name: src

params: 
  SEARCH_PATH: "src/my-chart"

run:
  path: src/helm/lint/lint_helm.sh
